services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_TUNNEL_URL: ${WEBHOOK_TUNNEL_URL}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_TRUSTED_PROXIES: loopback,linklocal,uniquelocal
      DB_TYPE: ${DB_TYPE}
      DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
      DB_POSTGRESDB_PORT: ${DB_POSTGRESDB_PORT}
      DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
      DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: ${REDIS_HOST}
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_GROUP_ID: ${TELEGRAM_GROUP_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./data/n8n:/home/node/.n8n
    depends_on:
      - postgres
      - redis

    n8n-worker:
      image: n8nio/n8n:latest
      container_name: n8n-worker
      user: "1000:1000"
      restart: unless-stopped
      environment:
        N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
        DB_TYPE: ${DB_TYPE}
        DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
        DB_POSTGRESDB_PORT: ${DB_POSTGRESDB_PORT}
        DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
        DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
        DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}

        EXECUTIONS_MODE: queue
        QUEUE_BULL_REDIS_HOST: ${REDIS_HOST}
        QUEUE_BULL_REDIS_PORT: ${REDIS_PORT}

        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
        TELEGRAM_GROUP_ID: ${TELEGRAM_GROUP_ID}
        OPENAI_API_KEY: ${OPENAI_API_KEY}

        GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
        TZ: ${TZ}
      depends_on:
        - redis
        - postgres
      volumes:
        - ./data/n8n:/home/node/.n8n

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRESDB_DATABASE}
      TZ: ${TZ}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRESDB_USER} -d ${DB_POSTGRESDB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: n8n_network

volumes:
  n8n_data:
  postgres_data:
  redis_data: